/**
 * Impeccable subagents deployed to `~/.omp/agent/agents/<name>.md`, where OMP's
 * task-agent discovery reads user-level definitions. The payload files are
 * generated by `bun run update-impeccable`, never hand-written: upstream ships
 * these definitions only in the Claude variant, so they are vendored through
 * the front-matter translation in `impeccable-agents.ts`.
 */
export const LOCAL_MANAGED_AGENTS = [
	"impeccable-finish-reviewer",
	"impeccable-documenter",
	"impeccable-asset-producer",
	"impeccable-manual-edit-applier",
] as const;
